src/disease/urls.py
from django.conf.urls import url

from .views import (
        DiseaseListView
        )

urlpatterns = [
    url(r'^$', DiseaseListView.as_view(), name="query"),
]

src/search/urls.py
from django.conf.urls import url

from .views import (
        SearchSymptomView,
        )

urlpatterns = [
    url(r'^$', SearchSymptomView.as_view(), name="query"),
]

src/symptomss/urls.py
from django.conf.urls import url

from .views import (
        SymptomListView
        )

urlpatterns = [
    url(r'^$', SymptomListView.as_view(), name="list"),

]

src/tcc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static

from symptomss.views import SymptomListView, symptom_list_view
from .views import home, about, contact, exam

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^about/', about, name='about'),
    url(r'^contact/', contact, name='contact'),
    url(r'^symptoms/', include(("symptomss.urls", "symptoms"), namespace="symptoms")),
    url(r'^search/', include(("search.urls", "search"), namespace="search")),
    url(r'^admin/', admin.site.urls),
    url(r'^exam/', exam, name='exam'),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/disease/models.py
from django.db import models

# Create your models here.

class Disease(models.Model):
    disease         = models.CharField(max_length=120)
    count           = models.IntegerField(null=True)
    # description     = models.TextField(default="Under construction")

    def __str__(self):
        return self.disease
    # def __str__(self):
        # return self.count
    # def __str__(self):
        # return self.description

src/disease_symptom/models.py
from django.db import models

# Create your models here.

src/symptoms/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Symptom(models.Model):
    symptom = models.CharField(max_length=120)

    def __str__(self):
        return self.symptom

src/symptomss/models.py
from django.db import models

# Create your models here.

class Symptom(models.Model):
    symptom         = models.CharField(max_length=120)

    # objects = SymptomManager()

    def __str__(self):
        return self.symptom

src/tcc/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()

class ContactForm(forms.Form):
    name 	= forms.CharField(
	           widget=forms.TextInput(
	    		attrs={
	    		"class":"form-control",
	    		"placeholder":"Your name"
	    		}
	    		)
    	)

    email 	= forms.EmailField(
	           widget=forms.EmailInput(
	    		attrs={
	    		"class":"form-control",
	    		"placeholder":"Your email"
	    		}
	    		)
    	)

    content = forms.CharField(
                widget=forms.Textarea(
    				attrs={
    				"class":"form-control",
    				"placeholder":"How can we help you?"
    				}
    				)
    	)

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if not "gmail.com" in email:
            raise forms.ValidationError("Email has to be a valid email.")
        return email

src/disease/views.py
from django.shortcuts import render

# Create your views here.

src/disease_symptom/views.py
from django.shortcuts import render

# Create your views here.

src/search/views.py
from django.views.generic import ListView
from django.shortcuts import render, get_object_or_404
from symptomss.models import Symptom

class SearchSymptomView(ListView):
    template_name = "search/view.html"

    def get_context_data(self, *args, **kwargs):
        context = super(SearchSymptomView, self).get_context_data(*args, **kwargs)
        query = self.request.GET.get('q')
        context['query'] = query
        return context

    def get_queryset(self, *args, **kwargs):
        request = self.request
        method_dict = request.GET
        query = method_dict.get('q', None)
        if query is not None:
            return Symptom.objects.filter(symptom__icontains=query)
        return Symptom.objects.all()

src/symptoms/views.py
from django.views.generic import ListView
from django.shortcuts import render, get_object_or_404

from .models import Symptom

class SymptomListView(ListView):
    template_name = "symptoms/list.html"

    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Symptom.objects.all()
    # queryset = Symptom.objects.all()

    # def get_context_data(self, *args, **kwargs):
    #     context = super(SymptomListView,self).get_context_data(*args,**kwargs)
    #     return context

def symptom_list_view(request):
    queryset = Symptom.objects.all()
    context = {
        'object_list': queryset
    }
    return render(request, "symptoms/list.html", context)

src/symptomss/views.py
from django.views.generic import ListView
from django.shortcuts import render, get_object_or_404

from .models import Symptom

class SymptomListView(ListView):
    template_name = "symptoms/list.html"

    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Symptom.objects.all()

def symptom_list_view(request):
    queryset = Symptom.objects.all()
    context = {
        'object_list': queryset
    }
    return render(request, "symptoms/list.html", context)

src/tcc/views.py
from django.conf import settings
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

from .forms import ContactForm

def home(request):
    context = {
        "content":"Homepage"
    }
    return render(request, 'home.html', context)

def about(request):
    context ={
        "title":"About us",
    }
    return render(request, 'about/view.html', context)

def contact(request):
    contact_form = ContactForm(request.POST or None)
    context ={
        "title":"Contact Page",
        "form": contact_form,
    }
    if contact_form.is_valid():
        name = contact_form.cleaned_data.get('name')
        email = contact_form.cleaned_data.get('email')
        message = contact_form.cleaned_data.get('content')
        subject = contact_form.cleaned_data.get('subject')
        from_email = email

        content = (("\nFrom: " + email+
                    "Subject: " + subject +
                    "Name: " + name +
                    +"\n" + message))

        send_mail(subject, content, from_email, ['lesprojeto@gmail.com'])

        print(contact_form.cleaned_data)
    return render(request, "contact/view.html", context)

def exam(request):
    return render(request, 'exam.html', {})

src/search/templates/search/snippets/search-form.html


<style>
/* O CSS foi deixado aqui pois o mesmo estava bugando a lista quando movido */


* {
  box-sizing: border-box;
}

#myInput {
  background-position: 10px 10px;
  background-repeat: no-repeat;
  width: 100%;
  font-size: 16px;
  padding: 12px 20px 12px 40px;
  border: 1px solid #ddd;
  margin-bottom: 12px;
}

#myTable {
  border-collapse: collapse;
  width: 100%;
  border: 1px  #ddd;
  font-size: 18px;
}

#myTable th, #myTable td {
  text-align: left;
  padding: 12px;
}

#myTable tr {
  border-bottom: 1px #ddd;
}

#myTable tr.header, #myTable tr:hover {
  background-color: #f1f1f1;
}
</style>

<input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for your symptoms">

<table id="myTable">
  {% for obj in object_list %}
  <tr>
    <td>
      {% include "symptoms/snippets/card.html" with instance=obj %}
      {# {% if forloop.counter|divisibleby:3 %} #}
    </td>
    {# {% endif %} #}
  {% endfor %}
  </tr>
</table>
<script>

function myFunction() {
  var input, filter, table, tr, td, i;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }
  }
}
</script>

src/symptoms/templates/symptoms/list.html

{% extends "base.html" %}

{% block content %}

    <div class="row">
      {% for obj in object_list %}
      <div class="col">
        {{forloop.counter}}
        {% include "symptoms/snippets/card.html" with instance=obj%}
        {% if forloop.counter|divisibleby:3 %}
      </div></div><div class="row"><div class="col-12"><hr></div>
        {% elif forloop.counter|divisibleby:3%}
            </div></div><div class="row"><div class="col-12"><hr></div>
        {% else %}
        </div>
        {% endif %}
      {% endfor %}

{% endblock content %}

src/symptoms/templates/symptoms/snippets/card.html
<div class="card" style="width: 18rem;">

  {% if instance.image %}
    <a href="{{instance.get_absolute_url}}" class="">
      <img class="card-img-top" alt="{{instance.title}} logo">
    </a>
  {% endif %}

  <div class="card-body">
    <h5 class="card-title">{{instance.symptom}}</h5>
    <a  class="btn btn-primary">Add to list</a>
  </div>

</div>

src/symptomss/templates/symptoms/list.html
{% extends "base.html" %}
{% block content %}

<div class="container">
  <div class="row no-gutters">
    {% for obj in object_list %}
    <div class="col-md-4">
      {% include "symptoms/snippets/card.html" with instance=obj%}
      {% if forloop.counter|divisibleby:2%}
    </div>
  </div>
  <div class="row no-gutters">
    {% else %}
  </div>
  {% endif %}
  {% endfor %}
</div>
{% endblock content %}

src/symptomss/templates/symptoms/snippets/card.html
<div class="card card-s">

 {% if instance.image %}
    <a href="{{instance.get_absolute_url}}" class="">
      <img class="card-img-top" alt="{{instance.title}} logo">
    </a>
  {% endif %}

  <div class="card-body">
    <h5 class="card-title">{{instance.symptom}}</h5>
    <a  class="btn btn-primary">Add <i class="fas fa-plus-circle fa-add"></i></a>
  </div>

</div>

src/templates/about/view.html
{% extends "base.html" %}

{% block content %}

<div class="text-center">
  <h2>{{title}}</h2>
</div>

<div class="container">
    <div class="About us">
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <p>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <p>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <p>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

  </div>
</div>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

{% endblock %}

src/templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

<link rel="stylesheet" href="{% static "css/main.css" %}">
<link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}">
<link rel="stylesheet" href="{% static "css/owl.theme.default.min.css" %}">

src/templates/base/footer.html
<footer>
<div class="footer">
  Todos os Direitos Reservados
</div>
   {% include "base/js.html" %}
</footer>

src/templates/base/js.html
{% load static %}
<!-- Optional JavaScript -->


<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script type="text/javascript" href="{% static "js/app.js" %}"></script>
<script type="text/javascript" href="{% static "js/owl.carousel.min.js" %}"></script>

src/templates/base/navbar.html
<header>
  <nav class="navbar navbar-expand-lg menu">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">Web Doctor | Disease Prediction System</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse list-menu" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'search:query' %}">Symptoms List</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">About us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contact' %}">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="modal" data-target="#exampleModalCenter"><i class="fa fa-user-circle login-fa"></i></a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document" >
      <div class="modal-content">
        <form action="/admin/login/?next=/admin/" method="post" id="login-form"><input type='hidden' name='csrfmiddlewaretoken' value='4rtiBvib676OiRrU1G1iV9gnxymhCJVwt5eK49hOkq4adRkb30mAWHKwW4JK38Gx' />
          {% csrf_token %}
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Login</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="input-group input-group-sm mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="inputGroup-sizing-sm" for="id_username">Username:</span><input type="text" name="username" autofocus maxlength="254" required id="id_username" />
            </div>
          </div>
          <div class="input-group input-group-sm mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="inputGroup-sizing-sm" for="id_password">Password:</span>
              <input type="password" name="password" required id="id_password" />
              <input type="hidden" value="/admin/" name="next" class="form-control" aria-label="Small" aria-describedby="inputGroup-sizing-sm">
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary"  value="Log in">Login</button>
        </div>
      </div>
    </div>
  </div>


<!-- Contact form

<div class="modal fade" id="modalContactForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header text-center">
                <h4 class="modal-title w-100 font-weight-bold">Write to us</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body mx-3">
                <div class="md-form mb-5">
                    <i class="fa fa-user prefix grey-text"></i>
                    <input type="text" id="form34" class="form-control validate">
                    <label data-error="wrong" data-success="right" for="form34">Your name</label>
                </div>

                <div class="md-form mb-5">
                    <i class="fa fa-envelope prefix grey-text"></i>
                    <input type="email" id="form29" class="form-control validate">
                    <label data-error="wrong" data-success="right" for="form29">Your email</label>
                </div>

                <div class="md-form mb-5">
                    <i class="fa fa-tag prefix grey-text"></i>
                    <input type="text" id="form32" class="form-control validate">
                    <label data-error="wrong" data-success="right" for="form32">Subject</label>
                </div>

                <div class="md-form">
                    <i class="fa fa-pencil prefix grey-text"></i>
                    <textarea type="text" id="form8" class="md-textarea form-control" rows="4"></textarea>
                    <label data-error="wrong" data-success="right" for="form8">Your message</label>
                </div>

            </div>
            <div class="modal-footer d-flex justify-content-center">
                <button  class="btn btn-unique">Send <i class="fa fa-paper-plane-o ml-1"></i></button>
            </div>
        </div>
    </div>
</div>

<div class="text-center">
    <a href="" class="btn btn-default btn-rounded mb-4" data-toggle="modal" data-target="#modalContactForm">Launch Modal Contact Form</a>
</div>
-->
</header>

src/templates/contact/view.html
{% extends "base.html" %}

{% block content %}

<div class="container">
  <div class="row">
      <div class="col">
        <div class="col-sm-6 col-12 contact">
          <div class="top-contact">
            <div class="col-8 left">
              <h3>Contact us</h3>
              <p>
                Fill in the form below to send us a message
              </p>
            </div>
            <div class="col-4 right">
              <i class="fas fa-envelope"></i>
            </div>
          </div>
          <form method="post"> {% csrf_token %}
            {{form}}
            <button type="submit" class="btn btn-default">Send Message</button>
          </form>
        </div>
    </div>
  </div>
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

{% endblock %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% include "base/css.html" %}
  </head>
  <body>
    {% include "base/navbar.html" with brand_name='webDoctor' %}
    {% block content %}{% endblock %}
    {% include "base/js.html" %}

  </body>
</html>

templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="{% static "css/main.css" %}">

templates/base/js.html
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

templates/base/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#"><h1>{{brand_name}}</h1></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        {# About us ainda não existe #}
        <a class="nav-link" href="{% url 'about' %}">About us</a> 
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'contact' %}">Contact</a>
      </li>
    </ul>
  </div>
</nav>

templates/home.html
{% extends 'base.html' %}
{% load static %}

<title>Home page template</title>
{% block content %}
  <div class="text-center">
    <h1>{{content}}</h1>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div id="content">
            <h1>Web Doctor</h1>
            <h3>The best Disease Prediction Website</h3>
            <hr>
            <button class="btn btn-default">
              <a class="btn-link" href="{% url 'symptoms:list' %}">Symptoms</a>
            </button>

          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}


<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/main.css" %}">

  </head>
  <body>
  </body>
</html>